[package]
name = "longest_valid_parentheses"
version = "0.1.0"
authors = ["Ainevsia <zhipengxu@sjtu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
